language: php

matrix:
  include:
    - php: 7.0
    - php: 7.1

before_script:
  - composer self-update
  - composer install --prefer-source

script:
    - composer validate
    - ./vendor/bin/phing security:check
    - ./vendor/bin/phing sniff
    - ./vendor/bin/phing unit
