language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source

script:
    - composer validate
    - ./vendor/bin/phing security:check
    - ./vendor/bin/phing sniff
    - ./vendor/bin/phing unit
